package mental.magic;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author jacks
 */
public class MentalMagic extends JFrame {

    private List<String> castCards = new ArrayList<String>();
    public MentalMagic(){
        init();
        setSize(800,350); 
        setVisible(true); 
        setResizable(false);
    }
    /**
     * Initializes the applet MentalMagic
     */
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MentalMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MentalMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MentalMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MentalMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jTextFieldCardName = new javax.swing.JTextField();
        jButtonCast = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonCheck = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jLabelConsole = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCastList = new javax.swing.JTextArea();
        jLabelCardsCast = new javax.swing.JLabel();

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsole);

        jTextFieldCardName.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTextFieldCardName.setText("Card to Cast");
        jTextFieldCardName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCardNameActionPerformed(evt);
            }
        });

        jButtonCast.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jButtonCast.setText("Cast");
        jButtonCast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCastActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonCheck.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jButtonCheck.setText("Check");
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckActionPerformed(evt);
            }
        });

        jButtonRemove.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jLabelConsole.setText("Console");

        jTextAreaCastList.setColumns(20);
        jTextAreaCastList.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCastList);

        jLabelCardsCast.setText("Cards Cast");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCardName, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCheck)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemove)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCast)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelConsole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCardsCast)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsole)
                    .addComponent(jLabelCardsCast))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCast)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonCheck)
                    .addComponent(jButtonRemove))
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCastActionPerformed
        String currentCard=jTextFieldCardName.getText().toLowerCase();
        if (castCards.contains(currentCard)) {
            jTextAreaConsole.append(currentCard + " CANNOT BE CAST"+"\n");
        } else {
            castCards.add(currentCard);
            jTextAreaConsole.append(currentCard + " IS CAST"+"\n");
        }
        jTextFieldCardName.setText("");
        jTextAreaCastList.setText(castCards.toString());
    }//GEN-LAST:event_jButtonCastActionPerformed

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckActionPerformed
        String currentCard=jTextFieldCardName.getText().toLowerCase();
        if (castCards.contains(currentCard)) {
            jTextAreaConsole.append(currentCard + " has ALREADY been cast"+"\n");
            jTextFieldCardName.setText("");
        } else {
            jTextAreaConsole.append(currentCard + " CAN be cast"+"\n");
        }
    }//GEN-LAST:event_jButtonCheckActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextAreaConsole.setText("Game has been reset"+"\n");
        jTextFieldCardName.setText("");
        castCards.clear();
        jTextAreaCastList.setText(castCards.toString());

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        String currentCard=jTextFieldCardName.getText().toLowerCase();
        if (castCards.contains(currentCard)) {
            castCards.remove(currentCard);
            jTextAreaConsole.append(currentCard + " has been REMOVED"+"\n");
        } else {
            jTextAreaConsole.append(currentCard + " has NOT been cast"+"\n");
        }
        jTextFieldCardName.setText("");
        jTextAreaCastList.setText(castCards.toString());
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jTextFieldCardNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCardNameActionPerformed
        jTextFieldCardName.setText("");
    }//GEN-LAST:event_jTextFieldCardNameActionPerformed
    public static void main(String [] args)
	{
            MentalMagic m = new MentalMagic();
            m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            m.setTitle("Mental Magic Machine");
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCast;
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelCardsCast;
    private javax.swing.JLabel jLabelConsole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCastList;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JTextField jTextFieldCardName;
    // End of variables declaration//GEN-END:variables
}
